### ISSUE TITLE
Refactor to facilitate use of code as JavaScript interface to FDSN web services?

### ISSUE THREAD

**Issue by baagaard-usgs** [crotwell/seisplotjs#1]
I found seisplotjs and its dependencies (seisplotjs-*) while searching to see if anyone had made a JavaScript interface to FDSN web services. Your code looks like it could be very useful, but it doesn't look like it is easily used as a JavaScript library. For example, it would be very convenient to just fork a single repo that is limited to the JavaScript interfaces to the FDSN web services. I realize there are ways to use git submodules to create a single repository on my end, but that still results in each piece in a separate directory.

Have you considered reorganizing the code so that the interfaces to FDSN web services all sit in one directory within a single repo? This would make it easier to fork and facilitate contributions from others via pull requests.

**Comment by crotwell** [comment]
Yes, have thought about it, not sure my original idea of lots of small pieces was the best. On the other hand one big repo/javascript seemed bad in that someone that just wanted the fdsn web services would also pull in lots of other dependencies and keeping one github repo per npm package seemed desirable. There might be a better place in the middle, I'll think some more about it. Also this was more or less my first foray into javascript libraries and the packaging ecosystem. Much less clear how to do this well imho, best practices still seem to be evolving...  

On the other hand, if you just want to use the seisplotjs stuff, then you can grab either individual pieces or the umbrella project via npm, ex 
[https://www.npmjs.com/package/seisplotjs](https://www.npmjs.com/package/seisplotjs)
[https://www.npmjs.com/package/seisplotjs-fdsnevent](https://www.npmjs.com/package/seisplotjs-fdsnevent)

**Comment by crotwell** [comment]
as of version 2.0, it is all in one repo, keeping separate repos was too much trouble.
