### ISSUE TITLE
WebSocket Over SSL Connection

### ISSUE THREAD

**Issue by Mytonn** [crotwell/seisplotjs#2]
Hello;

I get a "Error: SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS." error when I choose the SSL connection for WebSocket. The same error [here](https://crotwell.github.io/seisplotjs/tutorial/tutorial7.html) there is also. Is there any solution for running WebSocket connection over SSL?

**Comment by crotwell** [comment]
Changing the websocket url from ws:// to wss:// will create a secure websocket and get around browser security restriction for https pages. However, of course, the server you want to contact must also support secure websockets. Unfortunately the IRIS server, rtserve.iris.washington.edu, only supports unsecure websockets. I am unaware of the status of other seedlink servers.
