### ISSUE TITLE
Got Warning while import seisplotjs

### ISSUE THREAD

**Issue by Coder73-avi** [crotwell/seisplotjs#34]
WARNING in ./node_modules/oregondsp/kotlin/oregondsp.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/abhishek/Documents/Abhishek/src/main/kotlin/com/oregondsp/signalProcessing/filter/iir/SecondOrderSection.kt' file: Error: ENOENT: no such file or directory, open '/home/abhishek/Documents/Abhishek/src/main/kotlin/com/oregondsp/signalProcessing/filter/iir/SecondOrderSection.kt'

WARNING in ./node_modules/oregondsp/kotlin/oregondsp.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/abhishek/Documents/Abhishek/src/main/kotlin/com/oregondsp/signalProcessing/filter/iir/ThiranAllpass.kt' file: Error: ENOENT: no such file or directory, open '/home/abhishek/Document

(more then 160 warnings)

got warning while importing seisplotjs in react app (used to create-react-app) 
but all function are working fine How should we fixed this warning

need to know is it issue or something, because I'm using seisplotjs for visualize seiscomp data as graph

**Comment by crotwell** [comment]
Did you close the issue because you figured out the problem, or should it be reopened?

If it should still be open, can you give me more information about how I can reproduce the issue?

**Comment by Coder73-avi** [comment]
I just figured out for fixing the issue,  i just put GENERATE_SOURCEMAP=false
in .env file, after putting that all warning are gone, thank you for response.
