### ISSUE TITLE
seismographconfig ySublabel not set properly

### ISSUE THREAD

**Issue by Coder73-avi** [crotwell/seisplotjs#35]
while seing ySublabel as unit it got default value "cenerted count" is something wrong with my code?

`
const seisConfig = new sp.seismographconfig.SeismographConfig()
seisConfig.title = ''    
seisConfig.xLabel = 'Time'
if(channel){ seisConfig.xSublabel = `(${channel})` }
seisConfig.lineColors = ['skyblue', "#1B1212"]
seisConfig.ySublabel= 'unit'
`

and need information about spectrogram graph for fft visualization like raspberryshake

thank you !

**Comment by crotwell** [comment]
You also need
```
seisConfig.ySublabelIsUnits = false;
```
to prevent it from trying to calculate the sublabel by using the units in the seismogram. 

I will fix this so it happens automatically in next version.

See tutorial 5 for displaying fft amp and phase. Seisplotjs does not have a spectrogram function yet.
