### ISSUE TITLE
Changing display columns from fdsnevent.EventQuery()

### ISSUE THREAD

**Issue by rbeerster** [crotwell/seisplotjs#36]
I would like to customize the columns displayed from fdsnevent.EventQuery().  It appears that this is done using infotable.QuakeQuery.  However, I cannot get this to work.  In looking at the code, I did notice that https://github.com/crotwell/seisplotjs/blob/2c7e794a109ebf90d2cdbc774bc6ea15918d07ac/src/infotable.ts#L301 should likely be:
```
     this._quakeList.forEach(q => {
```
Here is the code I am working on:
```
import { fdsnevent, infotable, luxon, util } from '/js/seisplotjs_3.1.3_standalone.mjs';

const minMagnitude = 5.0;
document.querySelector('sp-min-magnitude').textContent = minMagnitude;

const searchEnd = luxon.DateTime.utc();
const dayPeriod = luxon.Duration.fromISO('P2D');
const searchWindow = util.durationEnd(dayPeriod, searchEnd);

const myColumnLabels = new Map();
myColumnLabels.set(infotable.QUAKE_COLUMN.TIME, 'Time');
// myColumnLabels.set(infotable.QUAKE_COLUMN.LAT, "Lat");
// myColumnLabels.set(infotable.QUAKE_COLUMN.LON, "Lon");
// myColumnLabels.set(infotable.QUAKE_COLUMN.MAG, "Mag");
// myColumnLabels.set(infotable.QUAKE_COLUMN.MAGTYPE, "Type");
// myColumnLabels.set(infotable.QUAKE_COLUMN.DEPTH, "Depth");
myColumnLabels.set(infotable.QUAKE_COLUMN.DESC, 'Description');
myColumnLabels.set(infotable.QUAKE_COLUMN.EVENTID, 'EventId');

console.log(`myColumnLabels : `, myColumnLabels);

const quakeQuery = new fdsnevent.EventQuery()
  .protocol('https:')
  .minMag(minMagnitude)
  .timeRange(searchWindow);

quakeQuery
  .query()
  .then((quakes) => {
    const qTable = new infotable.QuakeTable(quakes, myColumnLabels).draw();
    document.querySelectorAll('sp-quake-table').forEach((q) => {
      q.quakeList = quakes;
    });
    return quakes;
  })
  .catch((e) => {
    pEl.textContent = e;
    console.assert(false, e);
  });
```
Any assistance you can provide would be appreciated.

**Comment by rbeerster** [comment]
Am I understand correctly that with the second example you cannot change the columns displayed?  If so, feel free to close this. Otherwise, an example using the <sp-quake-table></sp-quake-table> in the html would be appreciated. Thanks again for both the code and the assistance.

**Comment by rbeerster** [comment]
Sorry I did not preview the text before submitting.  An example using:```<sp-quake-table></sp-quake-table>```

**Comment by crotwell** [comment]
You can set columns in either case, just that if you use the querySelector style, you do not have a constructor and so have to set it directly:
```
    const qTable = document.querySelector('sp-quake-table');
    qTable.columnLabels = myColumnLabels;
```

**Comment by rbeerster** [comment]
Thanks! I think I finally understand this now.
