### ISSUE TITLE
Connection to own SeedLink Server

### ISSUE THREAD

**Issue by nchazarra** [crotwell/seisplotjs#4]
Hi, 

I'm trying to plot my own seismograms on my local machine. I'm running ringerver on my network, but can't find the way to make a connection to my ringserver and plot the seismograms. Is it possible to plot waveforms from a SeedLink server? If so, how?

I tried to use the examples, but maybe I'm missing something while writing my own web.

Thanks.

**Comment by crotwell** [comment]
Yes it is possible. Without knowing more about the error you saw and your configuration it is hard to help. Check the broswers console and see if anything useful is printed.

The things to check first are that your ringserver is set up with a ListenPort and you don't have a firewall blocking connections. Test by pointing your browser to get the id, for example:
```
http://eeyore.seis.sc.edu:6382/id
```
Seisplotjs running in a browser can only do websockets, not regular sockets, so if you can't do the http:// then the ws:// won't work.

Also you need cors header set up correctly.I have in my ringserver config
```
ListenPort 6382
WebRoot /data/scsn/www/ringserver-web
HTTPHeader "Access-Control-Allow-Origin: *"
HTTPHeader "Cache-Control: no-cache"
```

Lastly, a page loaded with https is not allowed to connect to an insecure web socket, so if you are loading via https, you also need to connect to the ringserver with wss

Good luck

**Comment by nchazarra** [comment]
Hi,

First, thanks for your quick answer. My SeedLink server was working (I tested it with the address you told me and I got the correct answer "ringserver/2020.075 Organization: Rojales"), but not my code. I was trying to adapt the example 7 of the documentation for connecting to my SeedLink server, but my javascript knowledge is quite basic and obviuosly that is the problem. I will try to ask a friend to help me with the code.

Thanks!!

**Comment by nchazarra** [comment]
Hi again,

I tried to adapt one of the examples using this configuration:

if (wsProtocol == 'wss:' && host == IRIS_HOST) {
  console.log("IRIS currently does not support connections from https pages, I will attempt anyway, but you may wish to try from a http page instead.");
}

var my_server = "myserver";
var host = my_server;
var port = 18000;
var seedlinkUrl = wsProtocol+"//"+host+(port==18000?'':'80');
console.log("URL: "+seedlinkUrl);

var config = [
  'STATION ROJ01 ES',
  'SELECT 00EHE',
   ];


//wp.createPlotsBySelector('div.myseisplot');
console.log("before select");

But I seem not able to connect. These are the errors shown in the console:

![image](https://user-images.githubusercontent.com/7488275/202773955-f3709942-c1b8-496c-98c4-dbba9f5f75da.png)

**Comment by crotwell** [comment]
The URL looks invalid to me. It should be the same as the URL you used to test the ringserver id, but with http replaced with ws, so
```
http://eeyore.seis.sc.edu:6382/id
```
becomes
```
ws://eeyore.seis.sc.edu:6382
```

You need to give the actual DNS name of your machine instead of 'myserver':
```
var my_server = "myserver";
```

**Comment by crotwell** [comment]
Try
```
ws://homeassistant.local:18000/seedlink
```

**Comment by nchazarra** [comment]
Hi,

Thanks again. That was the solution, adding /seedlink in the end.

Greetings and thanks for your help.
